name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build
      env:
        CGO_ENABLED: 0
      
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.HOST}}
        username: root
        password: ${{ secrets.SSH_PWD }}
        port: 22
        source: "common"
        target: "/root"
        
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: root
        password: ${{ secrets.SSH_PWD }}
        port: 22
        script: |
          mkdir -p /home/go/common
          cd /home/go/common
          rm -rf common
          mv /root/common ./
          chmod 777 common
          nohup ./common &